name = "tractor-store-blueprint"
main = "src/server.cloudflare.js"
compatibility_date = "2024-03-12"

[site]
bucket = "./public"

  [[site.headers]]
  for = "*"
  [site.headers.values]
  Cache-Control = "public, max-age=3600"
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "*"